import numpy as np 
n=np.array([1,2,3,4,5])
print(n)
sum=sum(n)
print("Total_sum",sum)
prod=np.prod(n)
print("Product",prod)
mean=np.mean(n)
print("Mean : ",mean)
Std=np.std(n)
print("Standard_devation : ",Std)
m=np.median(n)
print("Median : ",m)
range=np.ptp(n)
print("Range : ",range)
max=np.max(n)
print("maxmimum",max)
min=np.max(n)
print("maxmimum",min)